language: objective-c
osx_image: xcode7
script:
  xctool
  -project apps/AffdexMe/AffdexMe.xcodeproj
  -scheme AffdexMe
  -sdk iphonesimulator
  -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
  build 
  test
  ONLY_ACTIVE_ARCH=NO
  CODE_SIGN_IDENTITY=""
  CODE_SIGNING_REQUIRED=NO
before_install:
  - brew update
  - brew uninstall xctool && brew install --HEAD xctool
  - wget http://affdex-sdk-dist.s3-website-us-east-1.amazonaws.com/ios/download_sdk.html
  - tar xvf download_sdk.html
  - cp -R affdex-sdk/Framework_Device/Affdex.framework frameworks/
